### ISSUE TITLE
generate_tsv_36 error

### ISSUE THREAD

**Issue by sileod** [idejie/bottom-up-attention-colab#1]
Hi, thank you for your work !
I changed `generate_tsv.py` to generate_tsv_36.py since the former didn't exist
So when I run the following cell in the colab
```
!python tools/generate_tsv_36.py --split flickr30k --def /content/models/vg/ResNet-101/faster_rcnn_end2end_final/test.prototxt --net /content/resnet101_faster_rcnn_final_iter_320000.caffemodel --out 'drive/My Drive/f30k_resnet101_faster_rcnn_genome.tsv' --cfg /content/experiments/cfgs/faster_rcnn_end2end_resnet.yml
```

I get:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "tools/generate_tsv_36.py", line 185, in generate_tsv
    result = get_detections_from_im(net, im_file, image_id)
  File "tools/generate_tsv_36.py", line 90, in get_detections_from_im
    scores, boxes, attr_scores, rel_scores = im_detect(net, im)
  File "/content/tools/../lib/fast_rcnn/test.py", line 123, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/content/tools/../lib/fast_rcnn/test.py", line 104, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/content/tools/../lib/fast_rcnn/test.py", line 34, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'
```
Do you have an idea why ? Did someone manage to make the colab work ? Thank you !

**Comment by idejie** [comment]
I guess that it's a problem with the image reading error. Maybe it will help you to check the variables `im_file`, `im` and some related.

BTW, the `generate_tsv.py` was changed and resaved as `tools/generate_tsv_final.py`  and if you want the original codes about this file, you can go to the official repo:[/peteanderson80/bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention).

Feel free to ask me if any problem.
Bests!
